# Generated by Django 3.2.13 on 2023-12-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('partner_name', models.CharField(max_length=50)),
                ('result', models.CharField(blank=True, max_length=210, null=True)),
            ],
        ),
    ]
